# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-09 18:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pix', '0002_auto_20170509_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='likes_received', to=settings.AUTH_USER_MODEL),
        ),
    ]
